### ISSUE TITLE
Unknown files: Prototype0.bin and Door0.bin

### ISSUE THREAD

**Issue by Koalamana9** [MilkAndBanana01/godot-fps-template#1]
There is two unknown files in the project, Prototype0.bin and Door0.bin, what are they?

**Comment by MilkAndBanana01** [comment]
I believe that is the old prototype level and the old door model. It should have been removed but I guess I haven't removed them yet.

**Comment by MilkAndBanana01** [comment]
![image](https://user-images.githubusercontent.com/94128784/149054196-9af03c24-18bd-49d1-9766-2e4bb56f747d.png)
Cleaned it up. Thank you for submitting an issue.
